services:

  postgres:
    image: postgres:17-alpine
    container_name: novacommerce-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: novacommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - novacommerce-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: novacommerce-pgadmin

    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@novacommerce.com
      PGADMIN_DEFAULT_PASSWORD: Admin123!
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    ports:
      - "5050:80"

    depends_on:
      - postgres

    volumes:
      - pgadmin-data:/var/lib/pgadmin

    networks:
      - novacommerce-network


volumes:

  postgres-data:
  pgadmin-data:


networks:

  novacommerce-network:
    driver: bridge